### ISSUE TITLE
Add a flag on the sync to process the requests without user interaction.

### ISSUE THREAD

**Issue by mkuhnt** [alphatier-works/sfctl#35]
Currently the user needs to select the assignments for the sync. This prevents any kind of automation of the sync right now.

**Proposal**

The command line flag `-a / --all`

```
sfctl time sync -a
```

will directly sync all assignments configured in the current directory without prompting the user.

**Comment by VILATTI** [comment]
@mkuhnt ready for testing.
Version upgraded to 0.0.4

**Comment by mkuhnt** [comment]
works! thx.
