### ISSUE TITLE
Time sync only synchronizes from the middle of the month

### ISSUE THREAD

**Issue by kaikae** [alphatier-works/sfctl#41]
When running `sfctl time sync` some of the records seem to be dropped from the synchronization to starfish.
The call was only syncing from the second half of the month, dropping all the previous days, even though there were entries in the previous weeks.:
![image](https://user-images.githubusercontent.com/21221912/86209698-6cd8c480-bb73-11ea-8394-233cb9f3043b.png)
![image](https://user-images.githubusercontent.com/21221912/86209953-f38da180-bb73-11ea-8c99-86c28e73e4b4.png)

The total on sfctl output was matching with Toggl tho, but in starfish the total was missing exactly the entries of the days that were also missing from the sfctl console output.

EDIT:
@VILATTI and I did a quick debugging session - the issue is caused by the pagination so only the last 50 records are taken into account, so all the remaining ones are cut.

**Comment by VILATTI** [comment]
Will be fixed in version "1.0.1"

**Comment by mkuhnt** [comment]
gem was pushed and is ready for use.
